### ISSUE TITLE
Quick radius bug for 1D case 

### ISSUE THREAD

**Issue by tombewley** [SamPIngram/RipleyK#1]
Hi there - have been looking around for a good implementation of the K function and your one looks great! I'm actually using it for the 1D case, and I think I _might_ have spotted a small bug in your code here: 

https://github.com/SamPIngram/RipleyK/blob/a0811bd77bdc0f989e915a17934490c356a4fba5/ripleyk/ripleyk.py#L67

Should that read: `radius**2`?

**Comment by tombewley** [comment]
Apologies - in hindsight I think I'm actually wrong there!

**Comment by SamPIngram** [comment]
Hi Tom,

I'm glad you are finding the package useful. Good to see you solved the issue yourself and closed the issue. If you need anything further just shout 👍

Sam
